maintainer        "KidsRuby"
maintainer_email  "cookbooks@kidsruby.com"
license           "Apache 2.0"
description       "Cross-platform 2D game development library"
version           "0.1.0"
supports          "ubuntu"
recipe            "default", "Sets up libraries requied to build apps with Gosu"